### ISSUE TITLE
Error on Teleport

### ISSUE THREAD

**Issue by Tsudico** [Zoutelande/Fabric-Server-Essentials#1]
Minecraft version: 1.15.2
All of Fabric Modpack version: 2.7.0
Fabric API version: 0.5.1+build.294
Fabric Essentials version: 1.1.7

[17:34:27] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.class_1937.method_25953(Lnet/minecraft/class_2338;)Z
        at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.14) ~[?:?]
        at me.simon.commands.util.TeleportHelper.teleport(TeleportHelper.java:114) ~[FabricEssentials-1.1.7.jar:?]
        at me.simon.commands.util.TeleportHelper.lambda$teleport$0(TeleportHelper.java:56) ~[FabricEssentials-1.1.7.jar:?]
        at me.simon.commands.util.TeleportHelper.lambda$teleport$1(TeleportHelper.java:75) ~[FabricEssentials-1.1.7.jar:?]
        at me.simon.commands.util.SimpleScheduler.lambda$onTick$0(SimpleScheduler.java:17) ~[FabricEssentials-1.1.7.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_242]
        at me.simon.commands.util.SimpleScheduler.onTick(SimpleScheduler.java:15) ~[FabricEssentials-1.1.7.jar:?]
        at net.fabricmc.fabric.api.event.server.ServerTickCallback.lambda$null$0(ServerTickCallback.java:33) ~[5d44b6c0-567c-46d2-b3ba-19af228de509.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bde000$tick(MinecraftServer:4820) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer:835) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer:655) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by Devan-Kerman** [comment]
fixed https://github.com/Zoutelande/Fabric-Server-Essentials/pull/2
